version: '3'
services:
  strapi:
    build: .
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: 192.168.31.178
      DATABASE_PORT: 3306
      DATABASE_NAME: lupin_diagonostics
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 39883988
